{% set name = "camelot-py" %}
{% set version = "1.0.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/camelot_py-{{ version }}.tar.gz
  sha256: 62514bd9effaef39a34c850f4b09705a817be160483b028cc8cde14954721466
build:
  entry_points:
    - camelot = camelot.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python
requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.0.1
    - chardet >=5.1.0
    - numpy >=1.24.4
    - openpyxl >=3.1.0
    - pdfminer-six >=20240706
    - pypdf >=3.17,<6.0
    - pandas >=1.5.3
    - tabulate >=0.9.0
    - typing_extensions >=4.12.2
    - opencv >=4.7.0.68
    - pypdfium2 >=4
test:
  imports:
    - camelot
  commands:
    - pip check
    - camelot --help
  requires:
    - python {{ python_min }}
    - pip
about:
  home: http://camelot-py.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: PDF Table Extraction for Humans.

extra:
  recipe-maintainers:
    - vinayak-mehta
    - bosd
    - izahn
